FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get install -y cmake python3 python3-pip git g++ clang-tidy
RUN pip3 install conan
RUN conan remote add catchorg https://api.bintray.com/conan/catchorg/Catch2
RUN conan profile new default --detect
RUN conan profile update settings.compiler.libcxx=libstdc++11 default

WORKDIR /home
RUN git clone https://github.com/PinkySan/CI-Example.git --single-branch -b idea/issue-7-clang-tidy_checks

WORKDIR CI-Example
RUN mkdir build
WORKDIR build

RUN conan install ..
RUN cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..

RUN python3 /usr/bin/run-clang-tidy -checks="*"