name: Clang-tidy runner

on: [push, pull_request]

jobs:
  build:
    name: Clang-Tidy Runner
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install conan
          conan profile new default --detect
          sudo apt-get install clang-tidy
      - name: Display versions
        run: |
          cmake --version | head -n 1
          gcc --version | head -n 1
          conan --version | head -n 1
          clang-tidy --version | head -n 1
          conan profile show default
          cat /etc/lsb-release | grep "DISTRIB_DESCRIPTION"
      - name: install conan dependencies
        run: conan install . -if build -s compiler.libcxx=libstdc++11 -s build_type=Release
      - name: cmake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_TOOLCHAIN_FILE:PATH=./build/conan_paths.cmake
      - name: run clang-tidy
        run: |
          cd build
          python /usr/bin/run-clang-tidy -p . > clang-output.txt
          ls -al
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.0
        with: 
          path: ./build/clang-output.txt
          name: clang-results
          
  uploadClangTidy:
    runs-on: ubuntu-20.04
    needs: [build]
    steps:
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.9
        with:
          name: clang-results
      - name: Install dependencies
        run: |
          sudo apt-get install clang-tidy
          git clone https://github.com/PSPDFKit-labs/clang-tidy-to-junit.git
          ls -alh
      
          
        
      
    
      
